config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  devise_for :users

  resources :cities
  resources :cars, only: [:index, :view, :new, :create, :edit, :update, :destroy]

  resources :users do
    resources :categories do
      resources :expenses
    end
    resources :cars do
      resources :reservations
    end
  end
    
  # Defines the root path route ("/")
  root "splash#index"
end

app/views/shared/_footer.html.erb
<div class="footer-container">
  <%= link_to 'Add a New Category', new_user_category_path(@user), :class=>'footer-btn' %>
</div>

app/views/shared/_header.html.erb
<nav class='header-container'>
  <ul>
    <li>
      <%= link_to user_path(@user) do %>
        <%= image_tag image_path('hamburger-menu.jpg'), style: 'width: 4rem; height: 4rem;' %>
      <% end %>
    </li>
    <li>Login</li>
    <li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= button_to "Sign out with link", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= button_to "Sign in", new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Sign up", new_user_registration_path, class:"nav-link" %>
        </li>
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_header_categories.html.erb
<nav class='header-container'>
  <ul>
    <li>
      <%= link_to user_path(@user) do %>
        <%= image_tag image_path('hamburger-menu.jpg'), style: 'width: 4rem; height: 4rem;' %>
      <% end %>
    </li>
    <li class="nav-item">
      CATEGORIES
    </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= button_to destroy_user_session_path, method: :delete do %>
            <%= image_tag 'search.png', alt: 'Sign out', style: 'width: 4rem; height: 4rem;' %>
          <% end %>
        </li>
        <% else %>
        <li class="nav-item my-flex">
          <%= link_to "Login", new_user_session_path, class:"button" %>
          <%= link_to "Signup", new_user_registration_path, class:"button" %>
        </li>
      <% end %>
  </ul>
</nav>
<% if user_signed_in? %>
<div class="gift-credit-container details-heading">
  <h2>Gift credit</h2>
  <h2>$300</h2>
</div>
<% end %>

app/views/shared/_header_forms.html.erb
<nav class='header-container'>
  <ul>
    <li>
      <%= link_to user_path(@user) do %>
        <%= image_tag image_path('back_button.jpeg'), style: 'width: 4rem; height: 4rem;' %>
      <% end %>
    </li>
    <li class="nav-item">
      CATEGORIES
    </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= button_to destroy_user_session_path, method: :delete do %>
            <%= image_tag 'search-icon_blue.png', alt: 'Sign out', style: 'width: 4rem; height: 4rem;' %>
          <% end %>
        </li>
        <% else %>
        <li class="nav-item my-flex">
          <%= link_to "Login", new_user_session_path, class:"button" %>
          <%= link_to "Signup", new_user_registration_path, class:"button" %>
        </li>
      <% end %>
  </ul>
</nav>

app/views/shared/_login_header.html.erb
<nav class='header-container'>
  <ul>
    <li>
      <%= link_to users_path do %>
        <%= image_tag image_path('hamburger-menu.jpg'), style: 'width: 4rem; height: 4rem;' %>
      <% end %>
    </li>
    <li>Login</li>
    <li class="nav-item">
      <%= button_to "Log in", new_user_session_path, class:"nav-link" %>
    </li>
  </ul>
</nav>

app/views/shared/_sign_up_header.html.erb
<nav class='header-container'>
  <ul>
    <li>
      <%= link_to users_path do %>
        <%= image_tag image_path('hamburger-menu.jpg'), style: 'width: 4rem; height: 4rem;' %>
      <% end %>
    </li>
    <li>Sign up</li>
    <li class="nav-item">
      <%= button_to "Next", new_user_session_path, class:"nav-link" %>
    </li>
  </ul>
</nav>