config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  devise_for :users

  resources :cities
  resources :cars, only: [:index, :view, :new, :create, :edit, :update, :destroy]

  resources :users do
    resources :categories do
      resources :expenses
    end
    resources :cars do
      resources :reservations
    end
  end
    
  # Defines the root path route ("/")
  root "splash#index"
end

app/models/city.rb
class City < ApplicationRecord
  has_many :reservations
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: %i[show edit update destroy]

  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show; end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit; end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to city_url(@city), notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_url(@city), notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_city
    @city = City.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def city_params
    params.require(:city).permit(:name, :continent, :description)
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_city.html.erb
<div id="<%= dom_id city %>">
  <div class="item">
    <div class="item-details">
      <strong class="details-heading">
        <%= link_to city.name, city_path(city) %> 
        <%= city.description %>
      </strong>
      <small><%= time_ago_in_words(city.created_at) %></small>
    </div>
  </div>
</div>

app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Show this city", @city %> |
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cities</h1>

<div id="cities">
  <% @cities.each do |city| %>
    <%= render city %>
    <p>
      <%= link_to "Show this city", city %>
    </p>
  <% end %>
</div>

<%= link_to "New city", new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @city %>

<div>
  <%= link_to "Edit this city", edit_city_path(@city) %> |
  <%= link_to "Back to cities", cities_path %>

  <%= button_to "Destroy this city", @city, method: :delete %>
</div>