config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  devise_for :users

  resources :cities
  resources :cars, only: [:index, :view, :new, :create, :edit, :update, :destroy]

  resources :users do
    resources :categories do
      resources :expenses
    end
    resources :cars do
      resources :reservations
    end
  end
    
  # Defines the root path route ("/")
  root "splash#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses
  has_many :expenses, through: :category_expenses

  validates :name, presence: true, length: { minimum: 2 }

  has_one_attached :icon
  validate :validate_icon_presence

  def total_expense_amount
    expenses.any? ? expenses.sum(:amount) : 0
  end

  private

  def validate_icon_presence
    errors.add(:icon, 'Please upload an icon') unless icon.attached?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]
  load_and_authorize_resource except: [:destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  # GET /categories or /categories.json
  def index
    @user = current_user
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @user = current_user
    @categories = @user.categories
    @category = @user.categories.find(params[:id])
    @expenses = @category.expenses
    @expense = @user.categories.flat_map(&:expenses).find(params[:id])
  end

  # GET /categories/new
  def new
    @user = current_user
    @category = current_user.categories.new
  end

  # GET /categories/1/edit
  def edit
    @user = current_user
    @category = @user.categories.find(params[:id])
  end

  # POST /categories or /categories.json
  def create
    @user = current_user
    @category = current_user.categories.new(category_params)
    authorize! :create, @category

    respond_to do |format|
      if @category.save
        format.html { redirect_to user_url(@user), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    @user = current_user
    @category = current_user.categories.find(params[:id])

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to user_categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @user = current_user
    @category = @user.categories.find(params[:id])

    # Update foreign key references in category_expenses table
    @category.category_expenses.destroy_all

    # Then destroy the category
    @category.destroy

    respond_to do |format|
      format.html { redirect_to user_categories_url(@user), notice: 'Category was successfully destroyed.' and return }
      format.json { head :no_content }
    end

    @category.destroy
    respond_to do |format|
      format.html { redirect_to user_categories_url(@user), notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  def not_found
    render file: "#{Rails.root}/public/404.html", layout: false, status: 404
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, expense_ids: [])
  end
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <div class="item">
    <% if category.icon.attached? %>
      <%= image_tag category.icon, style: 'width: 50px; height: 50px;' %>
    <% end %>

    <div class="item-details">
      <strong class="details-heading">
        <%= link_to category.name, user_category_path(@user, category) %> 
        $<%= category.total_expense_amount %>
      </strong>
      <small><%= time_ago_in_words(category.created_at) %></small>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<div class="all-form">
<%= form_with(model: [user, category], url: user_categories_path(user)) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/categories/_form_add.html.erb
<div class="all-form">
<%= form_with(model: [user, category], url: user_categories_path(user)) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/categories/_form_edit.html.erb
<div class="all-form">
<%= form_with(model: [current_user, @category], url: user_category_path(current_user, @category), method: :patch) do |form| %>
  <% if @category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/categories/edit.html.erb
<%= render 'shared/header_forms' %>

<%= render "form_edit", category: @category %>

<br>

<div>
  <%= link_to "Show this category", user_category_path(@user, @category) %> |
  <%= link_to "Back to categories", user_categories_path(@user) %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<%= render 'shared/header_categories' %>

<div class="items-list">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>

<%= render 'shared/footer' %>

app/views/categories/new.html.erb
<%= render 'shared/header_forms' %>

<%= render "form_add", user: @user, category: @category %>

<br>

app/views/categories/show.html.erb
<div id="<%= dom_id @category %>">
  <p style="color: green"><%= notice %></p>

  <%= render 'shared/header' %>

  <div class="view-item-details">
    <div class="view-icon">
      <% if @category.icon.attached? %>
        <%= image_tag @category.icon, style: 'width: 10rem; height: 10rem;' %>
      <% end %>
    </div>
    <div class="my-flex">
      <strong>
        <%= link_to @category.name, user_category_path(@user, @category) %> 
      </strong>
      <small>
        <%= button_to 'Delete this category', [@user, @category], method: :delete, data: { confirm: 'Are you sure?' }, class: 'button-white', style: 'margin-right: 10px;' %>
        <%= link_to 'Edit this category', edit_user_category_path(user_id: @user.id, category_id: @category&.id), class: 'button-white' %>
        <%= link_to 'Add a New Expense', new_user_category_expense_path(user_id: @user.id, category_id: @category&.id), class: 'button-white' %>
      </small>
    </div>
  </div>

  <div class="">
    <ul>
      <% @category.expenses.each do |expense| %>
        <div class="view-item">
          <li class="my-flex">
            <%= link_to expense.name, user_category_expense_path(@user, @category, expense) %>
            <span class="left"><%= time_ago_in_words(expense.created_at) %></span>
            <% if can? :destroy, expense %>
              <%= button_to 'Delete this expense', url_for([@user, @category, expense]), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button-white', style: 'margin-right: 10px;' %>
              <%= link_to 'Edit this expense', edit_user_category_expense_path(@user, @category, expense), class: 'button-white' %>
            <% end %>
          </li>
          <li>$<%= expense.amount %></li>
        </div>
      <% end %>
    </ul>
  </div> 

  <div class="view-total-payment">
    <%= "TOTAL PAYMENT" %>
    $<%= @category.total_expense_amount %>
  </div>
</div>