config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  devise_for :users

  resources :cities
  resources :cars, only: [:index, :view, :new, :create, :edit, :update, :destroy]

  resources :users do
    resources :categories do
      resources :expenses
    end
    resources :cars do
      resources :reservations
    end
  end
    
  # Defines the root path route ("/")
  root "splash#index"
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :reservations

  validates :name, presence: true, length: { minimum: 2 }

  has_one_attached :icon
  validate :validate_icon_presence

  def total_reservation_amount
    reservations.any? ? reservations.sum(:total_amount_payable) : 0
  end

  private

  def validate_icon_presence
    errors.add(:icon, 'Please upload an icon') unless icon.attached?
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: %i[show edit update destroy]
  load_and_authorize_resource except: [:destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  # GET /cars or /cars.json
  def index
    @user = current_user
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
    @user = current_user
    @cars = @user.cars
    @car = @user.cars.find(params[:id])
    @reservations = @car.reservations
    @reservation = @user.cars.flat_map(&:reservations).find(params[:id])
  end

  # GET /cars/new
  def new
    @user = current_user
    @car = current_user.cars.new
  end

  # GET /cars/1/edit
  def edit
    @user = current_user
    @car = @user.cars.find(params[:id])
  end

  # POST /cars or /cars.json
  def create
    @user = current_user
    @car = current_user.cars.new(car_params)
    authorize! :create, @car

    respond_to do |format|
      if @car.save
        format.html { redirect_to user_url(@user), notice: 'Car was successfully created.' }
        # format.html { redirect_to frontendUrls[:reactCarsIndex], notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    @user = current_user
    @car = current_user.cars.find(params[:id])

    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to user_cars_url, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @user = current_user
    @car = @user.cars.find(params[:id])

    # Update foreign key references in car_reservations table
    @car.car_reservations.destroy_all

    # Then destroy the car
    @car.destroy

    respond_to do |format|
      format.html { redirect_to user_cars_url(@user), notice: 'Car was successfully destroyed.' and return }
      format.json { head :no_content }
    end

    @car.destroy
    respond_to do |format|
      format.html { redirect_to user_cars_url(@user), notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  def not_found
    render file: "#{Rails.root}/public/404.html", layout: false, status: 404
  end

  # Only allow a list of trusted parameters through.
  def car_params
    params.require(:car).permit(:name, :icon, :description, :facebook, :twitter, :website, :finance_fee,
                                :ption_to_purchase_fee, :total_amount_payable, :duration)
  end
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <div class="item">
    <% if car.icon.attached? %>
      <%= image_tag car.icon, style: 'width: 50px; height: 50px;' %>
    <% end %>

    <div class="item-details">
      <strong class="details-heading">
        <%= link_to car.name, user_car_path(@user, car) %> 
        $<%= car.total_reservation_amount %>
      </strong>
      <small><%= time_ago_in_words(car.created_at) %></small>
    </div>
  </div>
</div>

app/views/cars/_form_add.html.erb
<button onclick="openFormModal()">Open Form</button>

<!-- The Modal -->
<div id="myModal" class="modal">
  <div class="modal-content">



<div class="all-form">
<%= form_with(model: [user, car], url: user_cars_path(user)) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :facebook, style: "display: block" %>
    <%= form.text_field :facebook %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website %>
  </div>

  <div>
    <%= form.label :finance_fee, style: "display: block" %>
    <%= form.number_field :finance_fee %>
  </div>
  
  <div>
    <%= form.label :option_to_purchase_fee, style: "display: block" %>
    <%= form.number_field :option_to_purchase_fee %>
  </div>
  
  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>
  
  <div>
    <%= form.label :total_amount_payable, style: "display: block" %>
    <%= form.number_field :total_amount_payable %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>


 </div>
</div>

<script>
// JavaScript function to open the modal
function openFormModal() {
  var modal = document.getElementById('myModal');
  modal.style.display = 'block';
}

// Close the modal if the user clicks outside of it
window.onclick = function(event) {
  var modal = document.getElementById('myModal');
  if (event.target == modal) {
    modal.style.display = 'none';
  }
}
</script>

app/views/cars/_form_edit.html.erb
<div class="all-form">
<%= form_with(model: [current_user, @car], url: user_car_path(current_user, @car), method: :patch) do |form| %>
  <% if @car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>
      <ul>
        <% @car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/cars/delete.html.erb
<p style="color: green"><%= notice %></p>

<%# <%= render 'shared/backend/header_cars' %>

<div class="container-fluid">
  <h3>Cars List</h3>
  <%= link_to 'Add a New Car', new_user_car_path(@user), :class=>'btn btn-info btn-sm' %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Website</th>
        <th scope="col">Facebook</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @cars.each do |car| %>
        <tr>
          <td><%= link_to car.name, user_car_path(@user, car) %></td>
          <td><%= car.description %></td>
          <td><%= car.website %></td>
          <td><%= car.facebook %></td>
          <td>
            <%= link_to 'Show', user_car_path(@user, car), class: 'btn btn-info btn-sm' %>
            <%= link_to 'Edit', edit_user_car_path(user_id: @user.id, id: car.id), class: 'btn btn-primary btn-sm' %>
            <%= button_to 'Delete', [@user, car], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%# <%= render 'shared/backend/footer' %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render "form_edit", car: @car %>

<br>

<div>
  <%= link_to "Show this car", user_car_path(@user, @car) %> |
  <%= link_to "Back to cars", user_cars_path(@user) %>
</div>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  <h3>Cars created succssufully</h3>
</div>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render "form_add", user: @user, car: @car %>

<br>

app/views/cars/show.html.erb
<div id="<%= dom_id @car %>">
  <p style="color: green"><%= notice %></p>

  <%# <%= render 'shared/backend/header_cars' %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
        <div class="view-icon">
          <% if @car.icon.attached? %>
            <%= image_tag @car.icon, class: 'img-fluid' %>
          <% end %>
          <strong><%= link_to @car.name, user_car_path(@user, @car) %></strong>
          <small>
            <%= button_to 'Delete this car', [@user, @car], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm', style: 'margin-right: 10px;' %>
            <%= link_to 'Edit this car', edit_user_car_path(user_id: @user.id, car_id: @car&.id), class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Add a New Reservation', new_user_car_reservation_path(user_id: @user.id, car_id: @car&.id), class: 'btn btn-success btn-sm' %>
          </small>
        </div>
      </div>
      <div class="col-md-9">
        <h5 class="mb-3">Reservations</h5>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Date</th>
              <th scope="col">Time Ago</th>
              <th scope="col">Total Amount Payable</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @car.reservations.each do |reservation| %>
              <tr>
                <td><%= link_to reservation.created_at, user_car_reservation_path(@user, @car, reservation) %></td>
                <td><%= time_ago_in_words(reservation.created_at) %></td>
                <td>$<%= reservation.total_amount_payable %></td>
                <td>
                  <% if can? :destroy, reservation %>
                    <%= button_to 'Delete', url_for([@user, @car, reservation]), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
                    <%= link_to 'Edit', edit_user_car_reservation_path(@user, @car, reservation), class: 'btn btn-primary btn-sm' %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <div class="mt-3">
          <h5>Total Payment</h5>
          <p>$<%= @car.total_reservation_amount %></p>
        </div>
      </div>
    </div>
  </div>
</div>